"""Prepare offline iOS font assets from the exact packages in package-lock.json.

Fontsource owns the font definitions/binaries; this build step copies their
normal weight-axis subsets and licenses. It never performs a network request.
"""
import json
from pathlib import Path
import re
import shutil

PACKAGES = ('inter', 'sora', 'noto-sans-jp')
VERSION = '5.3.0'

def build_fonts(root: Path) -> None:
    destination = root / 'assets/fonts'
    destination.mkdir(exist_ok=True)
    css = ['/* Generated by build_ios_fonts.py from pinned Fontsource packages. Licenses are in assets/fonts. */']
    expected = set()
    for name in PACKAGES:
        package = root / 'node_modules/@fontsource-variable' / name
        if not (package / 'package.json').exists():
            raise SystemExit('Bundled iOS fonts are missing. Run npm ci before building.')
        metadata = json.loads((package / 'package.json').read_text())
        if metadata['version'] != VERSION:
            raise SystemExit(f'Unexpected {name} font version. Run npm ci to restore the pinned build inputs.')
        source = (package / 'wght.css').read_text()
        for filename in re.findall(r'url\(\./files/([a-z0-9-]+\.woff2)\)', source):
            shutil.copyfile(package / 'files' / filename, destination / filename)
            expected.add(filename)
        shutil.copyfile(package / 'LICENSE', destination / f'{name}-LICENSE.txt')
        css.append(source.replace(" Variable'", "'").replace('./files/', '../fonts/'))
    for stale in destination.glob('*.woff2'):
        if stale.name not in expected:
            stale.unlink()
    (root / 'assets/css/mode-atlas-fonts-native.css').write_text('\n\n'.join(css) + '\n')

if __name__ == '__main__':
    build_fonts(Path(__file__).resolve().parent)
